MyWebsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('app.urls_staff')),
    path('', include('customer.urls_customer'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Category(models.Model):
    #code = models.CharField(max_length=20, verbose_name='Mã danh mục', unique=True, null=True, blank=True)
    name = models.CharField(max_length=200, verbose_name='Tên danh mục', unique=True)
    slug = models.CharField(max_length=200, verbose_name='Slug danh mục', unique=True, null=True, blank=True)
    status = models.BooleanField(verbose_name='Trang thái')
    def __str__(self):
        return self.name

class Event(models.Model):
    code = models.CharField(max_length=10, verbose_name='Mã sự kiện', unique=True)
    name = models.CharField(max_length=220,verbose_name='Tên sự kiện')
    slug = models.CharField(max_length=200, verbose_name='Tên SEO sự kiện', null=True, blank=True)
    description = RichTextUploadingField(verbose_name='mô tả sự kiện', null=True, blank=True)
    start_date = models.DateTimeField(verbose_name='ngày bắt đầu')
    end_date = models.DateTimeField(verbose_name='ngày kết thúc')
    status = models.BooleanField(verbose_name='Trang thái sự kiện', default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Danh mục')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name='Sự kiện', null=True, blank=True)
    code = models.CharField(max_length=10, verbose_name='Mã', unique=True)
    name = models.CharField(max_length=200, verbose_name='Tên', unique=True)
    slug = models.CharField(max_length=200, verbose_name='Tên SEO',null=True, blank=True)
    image = models.ImageField(upload_to='static/images', verbose_name='Ảnh')
    #image_list = models.CharField(max_length=500, verbose_name='Ảnh chi tiết', null=True, blank=True)
    price = models.FloatField(verbose_name='giá gốc')
    sale_price = models.FloatField(default=None, verbose_name='giảm khuyến mãi', null=True, blank=True)
    content = RichTextUploadingField(verbose_name='mô tả', null=True, blank=True)
    status = models.BooleanField(verbose_name='trạng thái')

    def __str__(self):
        return self.name

def get_image_filename(instance, filename):
    name = instance.Product.name
    slug = slugify(name)
    return "static/images/%s-%s" % (slug, filename)
    
class ImagesProduct(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    #main_image = models.ImageField(upload_to='static/images/', verbose_name='ảnh chính', null=True, blank=True)
    image = models.ImageField(upload_to='static/images/', verbose_name='ảnh chi tiết')

class Customer(models.Model):
    code = models.CharField(max_length=10, verbose_name='Mã', unique=True)
    name = models.CharField(max_length=200, verbose_name='Tên')
    email = models.CharField(max_length=200, verbose_name='Email', unique=True)
    password = models.CharField(max_length=200, verbose_name='Mật khẩu')
    remember_token = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    code = models.CharField(max_length=10, verbose_name='Mã', unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, verbose_name='Mã khách hàng')
    phone = models.IntegerField(verbose_name='Số điện thoại')
    address = models.TextField(verbose_name='Địa chỉ giao hàng')
    order_note = models.TextField(verbose_name='Ghi chú đơn hàng') 
    created_order = models.DateTimeField(verbose_name='Ngày tạo đơn hàng')
    status = models.IntegerField(verbose_name='trạng thái')

    class OrderStatus:
        XacNhan = 0
        DangGiao = 1
        DaGiao = 2
        GiaoThatBai = 3
        HuyDonHang = 4

    def __str__(self):
        return self.code

class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="mã đơn hàng")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="sản phẩm")
    quantity = models.IntegerField(verbose_name="số lượng")
    price = models.FloatField(verbose_name="Giá")

class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="mã sản phẩm")
    name = models.CharField(max_length=200, verbose_name="tên người hỏi", null=True, blank=True)
    email = models.CharField(max_length=200, verbose_name="email người hỏi", null=True, blank=True)
    content = models.TextField(verbose_name='nội dung')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')

    def __str__(self):
        return self.content

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name="mã bình luận")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="mã người trả lời")
    content = models.TextField(verbose_name="nội dung")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')

    def __str__(self):
        return self.content



class Sale(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name='mã sự kiện')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='mã sản phẩm')
    discount = models.FloatField(verbose_name="khuyến mại")
    same_price = models.FloatField(verbose_name="đồng giá", null=True, blank=True)

    
    

customer/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User # them model user

class CreateUserForm(UserCreationForm):
    password2 = forms.CharField(widget=forms.PasswordInput, label='nhập lại mật khẩu')
    class Meta:
        model = User

        fields = ['username','email', 'password1', 'password2']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name','slug', 'status')

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class PostForm(ModelForm):
    class Meta:
        model = Product
        fields = ['content']

class ImagesProductForm(ModelForm):
    image = forms.ImageField(label='ảnh chi tiết')
    #main_image = forms.ImageField(label='ảnh chính')
    class Meta:
        model = ImagesProduct
        fields = ('image',)

customer/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User # them model user

class CreateUserForm(UserCreationForm):
    password2 = forms.CharField(widget=forms.PasswordInput, label='nhập lại mật khẩu')
    class Meta:
        model = User

        fields = ['username','email', 'password1', 'password2']

app/templates/category/add.html
 {% extends '../base.html' %} {%block content %}

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Title</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {%csrf_token%}

                <div class="form-group">
                    <label for="exampleInputPassword1">Tên danh mục</label> {{ form.name }} {{form.name.errors}}
                </div>
                <div class="form-group">
                    <label>slug danh mục</label> {{ form.slug }} {{form.slug.errors}}
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Hiện thị :</label> {{ form.status }}
                </div>


                <button class="btn btn-primary" type="submit">Lưu lại</button>
            </form>
        </div>
        <!-- /.card-body -->
        <div class="card-footer"></div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>



{%endblock%} {%block js%}

<script type="text/javascript">
    $(document).ready(() => {
        $("form input").addClass("form-control");
    });

    $('input#id_name').keyup(function(event) {
        var title, slug;
        //Lấy text từ thẻ input title 
        title = $(this).val();
        //Đổi chữ hoa thành chữ thường
        slug = title.toLowerCase();
        //Đổi ký tự có dấu thành không dấu
        slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
        slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
        slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
        slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
        slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
        slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
        slug = slug.replace(/đ/gi, 'd');
        //Xóa các ký tự đặt biệt
        slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
        //Đổi khoảng trắng thành ký tự gạch ngang
        slug = slug.replace(/ /gi, "-");
        //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
        //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
        slug = slug.replace(/\-\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-/gi, '-');
        slug = slug.replace(/\-\-/gi, '-');
        //Xóa các ký tự gạch ngang ở đầu và cuối
        slug = '@' + slug + '@';
        slug = slug.replace(/\@\-|\-\@|\@/gi, '');
        //In slug ra textbox có id “slug”
        $('input#id_slug').val(slug);
    });
</script>
{%endblock%}

app/templates/category/edit.html
{% extends '../base.html' %} {%block content %}

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Sửa danh mục</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {%csrf_token%}

                <div class="form-group">
                    <label for="exampleInputPassword1">Tên danh mục</label> {{ form.name }} {{form.name.errors}}
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Hiện thị :</label> {{ form.status }}
                </div>


                <button class="btn btn-primary" type="submit">Lưu lại</button>
            </form>
        </div>
        <!-- /.card-body -->
        <div class="card-footer"></div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>



{%endblock%} {%block js%}
<script type="text/javascript">
    $(document).ready(() => {
        $("form input").addClass("form-control");
    });
</script>
{%endblock%}

app/templates/category/index.html
{% extends '../base.html' %} {%block content %}
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách danh mục</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width:15%">Mã danh mục</th>
                        <th>Tên danh mục</th>
                        <th>Trạng thái</th>
                        <th></th>
                    </tr>
                </tbody>
                {% for c in listCate %}
                <tr>
                    <td>{{ c.id }}</td>
                    <td>{{ c.name }}</td>
                    <td>
                        {%if c.status == 0%} ẩn {%endif%} {%if c.status == 1%} hiển thị {%endif%}
                    </td>
                    <td>
                        <a href="/staff/category/update/{{ c.id }}" class="btn btn-secondary">Sửa</a>
                        <a href="javascript:deleteCategory({{ c.id }})" class="btn btn-danger">Xóa</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer"></div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
{%endblock%} {%block js%}
<script type="text/javascript">
    function deleteCategory(id) {
        if (confirm('Bạn có muốn xóa?')) {
            location.href = '/staff/category/delete/' + id;
        }
    }
</script>
{%endblock%}

app/templates/demo.html
<form id="aa_form" method="post" action="" enctype="multipart/form-data">

    {% csrf_token %}
    {% for hidden in postForm.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {{ productForm.media }}
    {% for field in productForm %}
        {{ field }} <br />
    {% endfor %}

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}


    <input type="submit" name="submit" value="Submit" />
</form>

app/templates/events/add.html
 {% extends '../base.html' %} {%block content %}

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Title</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {%csrf_token%}
                {{ form.media }}
                <div class="form-group">
                    <label>Mã sự kiện</label> {{ form.code }} {{form.code.errors}}
                </div>
                <div class="form-group">
                    <label>Tên sự kiện</label> {{ form.name }} {{form.name.errors}}
                </div>
                <div class="form-group">
                    <label>Tên SEO sự kiện</label> {{ form.slug }} {{form.slug.errors}}
                </div>
                 <label>Mô tả</label>
                <div class="form-group">
                    {{ form.description }} {{form.description.errors}}
                </div>
                <div class="form-group">
                    <label>Ngày bắt đầu</label> {{ form.start_date }} {{form.start_date.errors}}
                </div>
                <div class="form-group">
                    <label>Ngày kết thúc</label> {{ form.end_date }} {{form.end_date.errors}}
                </div>

                <div class="form-group">
                    <label>Hiện thị :</label> {{ form.status }}
                </div>


                <button class="btn btn-primary" type="submit">Lưu lại</button>
            </form>
        </div>
        <!-- /.card-body -->
        <div class="card-footer"></div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>



{%endblock%} {%block js%}

<script type="text/javascript">
    $(document).ready(() => {
        $("form input").addClass("form-control");
    });

    $('input#id_name').keyup(function(event) {
        var title, slug;
        //Lấy text từ thẻ input title 
        title = $(this).val();
        //Đổi chữ hoa thành chữ thường
        slug = title.toLowerCase();
        //Đổi ký tự có dấu thành không dấu
        slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
        slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
        slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
        slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
        slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
        slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
        slug = slug.replace(/đ/gi, 'd');
        //Xóa các ký tự đặt biệt
        slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
        //Đổi khoảng trắng thành ký tự gạch ngang
        slug = slug.replace(/ /gi, "-");
        //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
        //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
        slug = slug.replace(/\-\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-/gi, '-');
        slug = slug.replace(/\-\-/gi, '-');
        //Xóa các ký tự gạch ngang ở đầu và cuối
        slug = '@' + slug + '@';
        slug = slug.replace(/\@\-|\-\@|\@/gi, '');
        //In slug ra textbox có id “slug”
        $('input#id_slug').val(slug);
    });
</script>
{%endblock%}

app/templates/events/index.html
{% extends '../base.html' %} {%block content %}
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách danh mục</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width:15%">Mã sự kiện</th>
                        <th>Tên sự kiện</th>
                        <th>Mô tả sự kiện</th>
                        <th>Ngày bắt đầu</th>
                        <th>Ngày kết thúc</th>
                        <th>Trạng thái</th>
                        <th></th>
                    </tr>
                </tbody>
                {% for e in events %}
                <tr>
                    <td>{{ e.code }}</td>
                    <td>{{ e.name }}</td>
                    <td>{{ e.description | safe }}</td>
                    <td>{{ e.start_date }}</td>
                    <td>{{ e.end_date }}</td>
                    <td>
                        {%if e.status == 0%} ẩn {%endif%} {%if e.status == 1%} hiển thị {%endif%}
                    </td>
                    <td>
                        <a href="/staff/event/update/{{ e.id }}" class="btn btn-secondary">Sửa</a>
                        <a href="javascript:deleteEvent({{ e.id }})" class="btn btn-danger">Xóa</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer"></div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
{%endblock%} {%block js%}
<script type="text/javascript">
    function deleteEvent(id) {
        if (confirm('Bạn có muốn xóa?')) {
            location.href = '/staff/event/delete/' + id;
        }
    }
</script>
{%endblock%}

app/templates/index.html
{% extends 'base.html' %}




{%block content %}
      <h2>Trang chu admin</h2>
{%endblock%}

app/templates/product/add.html
{% extends '../base.html' %} {%block content %}


<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thêm sản phẩm</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <form id="aa_form" method="post" action="" enctype="multipart/form-data">

                {% csrf_token %}
                {% for hidden in productForm.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                
                    {{ productForm.media }}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Mã sản phẩm</label> {{ productForm.code }} {{productForm.code.errors}}
                        </div>
                        <div class="form-group">
                            <label for="">Tên sản phẩm</label> {{ productForm.name }} {{productForm.name.errors}}
                        </div>
                        <div class="form-group">
                            <label for="">Tên SEO sản phẩm</label> {{ productForm.slug }} {{productForm.slug.errors}}
                        </div>
                        <div class="form-group">
                            <label for="">Danh mục sản phẩm</label> {{ productForm.category }} {{productForm.category.errors}}
                        </div>
                        <label for="">Mô tả sản phẩm</label>
                        <div class="form-group">
                             {{ productForm.content }} {{form.content.errors}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Chọn sự kiện</label> {{ productForm.event }} {{productForm.event.errors}}
                        </div>
                        <div class="form-group">
                            <label for="">Giá gốc sản phẩm</label> {{ productForm.price }} {{productForm.price.errors}}
                        </div>
                        <div class="form-group">
                            <label for="">Giá khuyến mại sản phẩm</label> {{ productForm.sale_price }} {{productForm.sale_price.errors}}
                        </div>

                        <div class="form-group">
                            <label for="">Hiển thị :</label> {{ productForm.status }}
                        </div>
                        <div class="form-group">
                            <label for="">Ảnh chính</label> {{ productForm.image }} {{productForm.image.errors}}
                        </div>
                        {{ formset.management_form }}
                        {% for form in formset %}
                            {{ form }}
                        {% endfor %}
                    </div>
                </div>



            

            
            
                <input type="submit" name="submit" value="Lưu" class="btn btn-primary" />
            </form>

        </div>
        <div class="card-footer" id="abc"><h3>ABC</h3></div>
    </div>
</section>



{%endblock%} 
{%block js%}
<script type="text/javascript">
    $(document).ready(() => {
        $("form input").addClass("form-control");
        $("form select").addClass("form-control");
        $( "#cke_id_content" ).css( "border", "3px solid red" );
    });
    document.getElementById("abc").style.color = "blue";

    $('input#id_name').keyup(function(event) {
        var title, slug;
        //Lấy text từ thẻ input title 
        title = $(this).val();
        //Đổi chữ hoa thành chữ thường
        slug = title.toLowerCase();
        //Đổi ký tự có dấu thành không dấu
        slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
        slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
        slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
        slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
        slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
        slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
        slug = slug.replace(/đ/gi, 'd');
        //Xóa các ký tự đặt biệt
        slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
        //Đổi khoảng trắng thành ký tự gạch ngang
        slug = slug.replace(/ /gi, "-");
        //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
        //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
        slug = slug.replace(/\-\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-/gi, '-');
        slug = slug.replace(/\-\-/gi, '-');
        //Xóa các ký tự gạch ngang ở đầu và cuối
        slug = '@' + slug + '@';
        slug = slug.replace(/\@\-|\-\@|\@/gi, '');
        //In slug ra textbox có id “slug”
        $('input#id_slug').val(slug);
    });
</script>
{%endblock%}

app/templates/product/detail.html
{% extends '../base.html' %}
{%block content %}
<div class="card-body">
    <table class="table table-bordered">
        <tbody>
            <tr>
                <th style="width:5%">Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Tên SEO sản phẩm</th>
                
                <th>Mô tả</th>
                <th>Ảnh 1</th>
                <th>Ảnh 2</th>
                <th>Ảnh 3</th>
                <th>Trạng thái</th>
                <th></th>
            </tr>
        </tbody>
        <tr>
            <td>{{ p.code }}</td>
            <td>{{ p.name }}</td>
            <td>{{ p.slug }}</td>
            
            <td>{{ p.content | safe }}</td>
            {% for img in imgP %}
                {% if p.code == img.product.code %}
                <td style="width: 25%;"><img src="/media/{{ img.image }}" style="max-width:200px; max-height:300px"></td>
                {% endif %}
            {% endfor %}
            <td>
                {%if p.status == 0%} ẩn {%endif%} {%if p.status == 1%} hiển thị {%endif%}
            </td>
            <td>
                <a href="/staff/product/update/{{ p.id }}" class="btn btn-secondary">Sửa</a>
                <a href="/staff/product/detail/{{ p.id }}" class="btn btn-success">Chi tiết</a>
                <a href="javascript:deleteCategory({{ p.id }})" class="btn btn-danger">Xóa</a>
            </td>
        </tr>
    </table>
</div>
{%endblock%}